/** @type {import("tailwindcss").Config} */
export default {
  content: ["./index.html", "./src/**/*.{js,ts,jsx,tsx}"],
  theme: {
    extend: {
      colors: {
        "on-primary-fixed-variant": "#7a3000",
        surface: "#fcf9f8",
        "surface-container-lowest": "#ffffff",
        "surface-container": "#f0eded",
        "on-primary-container": "#572000",
        "primary-fixed-dim": "#ffb693",
        "secondary-fixed": "#ffdad8",
        "tertiary-container": "#c19100",
        outline: "#8e7164",
        "inverse-surface": "#313030",
        "on-surface-variant": "#5a4136",
        "on-error": "#ffffff",
        "primary-container": "#ff6b00",
        "inverse-primary": "#ffb693",
        "secondary-fixed-dim": "#ffb3b1",
        "on-primary-fixed": "#351000",
        secondary: "#bb0027",
        "on-secondary-fixed-variant": "#92001d",
        "on-tertiary-container": "#402e00",
        "outline-variant": "#e2bfb0",
        "primary-fixed": "#ffdbcc",
        error: "#ba1a1a",
        "on-primary": "#ffffff",
        primary: "#a04100",
        "error-container": "#ffdad6",
        "surface-container-high": "#eae7e7",
        tertiary: "#785900",
        "tertiary-fixed-dim": "#fabd00",
        background: "#fcf9f8",
        "on-tertiary": "#ffffff",
        "tertiary-fixed": "#ffdf9e",
        "surface-variant": "#e5e2e1",
        "on-surface": "#1c1b1b",
        "on-tertiary-fixed-variant": "#5b4300",
        "surface-tint": "#a04100",
        "on-tertiary-fixed": "#261a00",
        "surface-dim": "#dcd9d9",
        "surface-container-low": "#f6f3f2",
        "on-background": "#1c1b1b",
        "on-secondary": "#ffffff",
        "on-error-container": "#93000a",
        "surface-container-highest": "#e5e2e1",
        "on-secondary-fixed": "#410007",
        "secondary-container": "#e51a38",
        "surface-bright": "#fcf9f8",
        "inverse-on-surface": "#f3f0ef",
        "on-secondary-container": "#fffbff",
      },
      fontFamily: {
        headline: ["Plus Jakarta Sans", "sans-serif"],
        body: ["Inter", "sans-serif"],
        label: ["Inter", "sans-serif"],
      },
      borderRadius: {
        DEFAULT: "1rem",
        lg: "2rem",
        xl: "3rem",
        full: "9999px",
      },
    },
  },
  plugins: [],
};
